<div id="header" class="header-container">
	<div class="header-content">
		<div class="top-header hidden-xs">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-lg-6 hidden-xs hidden-sm">	
						<div class="top-bar-left">
							<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-left-static')->toHtml(); ?>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 col-lg-6">
						<div class="top-bar-right">
							<div class="top-account has-child">
								<?php echo $this->getChildHtml("top.links"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	    <div class="header">
	    	<div class="header_main">
		    	<div class="header-main">
	          		<div class="container">
	          			<div class="row">
				          	<div class="wp-header">
								<div class="col-logo">
									<?php echo $this->getChildHtml("logo"); ?>
								</div>
				          		<div class="col-menu">
				          			<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
									<div class="menu_primary header-wrapper-sticky<?php echo (!$this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()) ? '' : ' enabled-header-sticky'; ?>">
										<div class="container-header-sticky">
											<div class="logo-sticky"><a href="<?php echo $block->getUrl('');?>" title="<?php echo __('Logo');?>"><img src="<?php echo ($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() != '') ? $this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() : $this->getViewFileUrl("images/logo_sticky.png");?>" alt="<?php echo __('Logo');?>"/></a></div>
											<div class="top-menu top-menu-sticky">
											  <?php echo $this->getChildHtml("custom.topnav"); ?>
											</div>
										</div>
									</div>
								</div>
					            <div class="top-search">
									<div class="flex-layout">
										<div class="col-header-action">
											<div class="toggle-search block block-search">
												<div class="block-content">
													<div class="dropdown">
														<div class="dropdown-toggle fixed-click-show-destop">
															<div class="top-search">
																<i class="icon-search"></i>
																<span class="text"><?php echo __('Search'); ?></span>
															</div>
														</div>
														<?php echo $this->getChildHtml("topSearch");?>
													</div>
												</div>
											</div>
											<div class="hidden-sm hidden-xs box_language">
												<div class="top-header">
													<?php echo $this->getChildHtml("store_language"); ?>
													<?php echo $this->getChildHtml("currency"); ?>
												</div>
											</div>
											<div class="mini-cart-wrapper shadowcart">
												  <div class="mini-carts">
													<?php echo $this->getChildHtml("minicart");?>
												  </div>
											 </div>
										</div>
									</div> 
					            </div>	
					        </div>	
					    </div>
			        </div>    
		    	</div>
		    </div>
	    </div>
	</div>
</div>

