<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-onsaleproduct">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_image_primary_small';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_image_primary_small';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-onslate-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = 2;
			?>	
			
				<div class="col-xs-12 col-onsale-right">
					<?php if($this->getConfig('title')){?>
						<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo $this->getConfig('title')?> <span class="sup-title"> <?php echo __('Products') ?></span></h2></div>
					<?php }?>
					<div class="row">
						<ul class="owl_onsale">
							<?php $_collectionSize = $_productCollection->count() ?>
							<?php $i=0; foreach ($_productCollection as $_product): ?>
								<?php if($i %$rows == 0) echo "<li class='item newproductslider-item'>"; ?>
									<div class="item-product-parent">
									<div class="item-product listview">
										<?php
										$productImage = $block->getImage($_product, $image);
										if ($pos != null) {
											$position = ' style="left:' . $productImage->getWidth() . 'px;'
												. 'top:' . $productImage->getHeight() . 'px;"';
										}
										?>
										<?php // Product Image ?>
										<div class="product-thumb">
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-thumb-link">
												<?php $productImageThumb = $block->getImage($_product, 'category_image_second_small');?>
												<span class="first-thumb">
													<?php echo $productImage->toHtml(); ?>
												</span>
												<?php $productType = $_product->getTypeID();
												if($productType == "simple"): ?>
													<span class="second-thumb">
														<?php echo $productImageThumb->toHtml(); ?>
													</span>
						                		<?php endif; ?>
											</a>
										</div>
										<div class="product-info">
											<?php
												$_productNameStripped = $block->stripTags($_product->getName(), null, true);
											?>
											<h3 class="product-name">
					 							<a title="<?php echo $_product->getName(); ?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-link">
													<?php echo $_product->getName(); ?>
												</a>
											</h3>
											<div class="product-rating">
												<?php if ($templateType): ?>
													<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
												<?php endif; ?>
											</div>
											<div class="info-price">
												<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
											</div>
											<div class="product-info-cart">
							                    <div class="actions-primary addcart-link">
							                      <?php if ($_product->isSaleable()): ?>
							                        <?php
							                          $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
							                          $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()]);
							                          $postParams = json_decode($postData, true);
							                          ?>
							                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
							                          <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
							                          <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
							                          <?php echo $block->getBlockHtml('formkey')?>
							                          <button type="submit"
							                              title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
							                              class="btn-add-to-cart action tocart">
							                            <span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
							                          </button>
							                        </form>
							                      <?php else: ?>
							                        <?php if ($_product->getIsSalable()): ?>
							                          <div class="stock available"><span><?php echo __('In stock') ?></span></div>
							                        <?php else: ?>
							                          <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
							                        <?php endif; ?>
							                      <?php endif; ?>
							                    </div>
				  							</div>
										</div>
									</div>
									<?php $i++;?>
								</div>
								<?php if($i %$rows == 0) echo "</li>"; ?>                  
							<?php endforeach; ?>
								<?php if($i %$rows != 0) echo "</li>"; ?>              
						</ul>
					</div>
				</div>
				<div class="col-xs-12 col-onsale-left">
				</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-onsaleproduct .owl_onsale").owlCarousel({
						lazyLoad:true,
						autoPlay : false,
						items : 2,
						itemsDesktop : [1366,2],
						itemsDesktopSmall : [1199,2],
						itemsTablet: [768,2],
						itemsMobile : [480,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : true,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
						afterAction: function(el){
						    this.$owlItems.removeClass('first-active')
						    this.$owlItems .eq(this.currentItem).addClass('first-active')  
					    }
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>