<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View\Comments
 */
?>
<?php if ($block->getCommentsType()) { ?>
<?php
    $json = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Serialize\Serializer\Json::class);
?>
<div class="block comments">
  <?php if ($block->getCommentsType() == 'facebook') { ?>
      <div id="fb-root"></div>
      <div class="post-comments clear">
          <div class="fb-comments" data-href="<?php echo $block->getPost()->getPostUrl() ?>" data-width="100%" data-numposts="<?php echo $block->getNumberOfComments() ?>"></div>
      </div>
      <?php
          $commentsConfig = [
              'type' => 'facebook',
              'locale' => $block->getLocaleCode(),
              'appId' => $block->getFacebookAppId()
          ];
      ?>
      <script type="text/x-magento-init">
          {
              "#fb-root": {
                  "Rokanthemes_Blog/js/comments-loader": <?php /* @escapeNotVerified */ echo $json->serialize($commentsConfig); ?>
              }
          }
      </script>
  <?php } elseif ($block->getCommentsType() == 'disqus') { ?>
        <div id="disqus_thread"></div>
        <?php
            $commentsConfig = [
                'type' => 'disqus',
                'pageUrl' => $block->getPost()->getPostUrl(),
                'identifier' => $block->getPost()->getUrl(),
                'shortname' => $block->getDisqusShortname()
            ];
        ?>
        <script type="text/x-magento-init">
            {
                "#disqus_thread": {
                    "Rokanthemes_Blog/js/comments-loader": <?php /* @escapeNotVerified */ echo $json->serialize($commentsConfig); ?>
                }
            }
        </script>
  <?php } ?>
</div>
<?php } ?>