<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post js template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
    $json = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Serialize\Serializer\Json::class);
    $addThisConfig = [
        'scriptUrl' => 'https://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4def63cd3cf37569',
        'settings' => [
            'data_track_clickback' => false,
            'ui_language' => 'en'
        ]
    ];
?>
<script type="text/x-magento-init">
    {
        "body": {
            "Rokanthemes_Blog/js/addthis-loader": <?php /* @escapeNotVerified */ echo $json->serialize($addThisConfig); ?>
        }
    }
</script>