<?php 
	$data = $block->getConfig();
?>
<?php if (isset($data['general']['enable_preloaded']) && $data['general']['enable_preloaded'] == 1){ ?>
<div id="loading-fixed">
	<div id="loading-center-fixed">
		<div id="loading-center-absolute-fixed">
			<div class="object-fixed" id="object_four"></div>
			<div class="object-fixed" id="object_three"></div>
			<div class="object-fixed" id="object_two"></div>
			<div class="object-fixed" id="object_one"></div>
		</div>
	</div>
</div>
<script type="text/x-magento-init">
{
	"#loading-fixed": {
		"Rokanthemes_Themeoption/js/beforebodyloader": {
			"delay": 500,
			"fallbackTimeout": 1000
		}
	}
}
</script>
<?php } ?>