<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (sizeof($block->getTerms()) > 0): ?>
    <ul class="search-terms">
        <?php foreach ($block->getTerms() as $_term): ?>
            <li class="item">
                <?php
                    $relativeSize = ($_term->getRatio() * 70) + 75;
                    $normalizedSize = (int)round($relativeSize / 5) * 5;
                    $normalizedSize = max(50, min(200, $normalizedSize));
                    $sizeClass = 'search-term-scale-' . $normalizedSize;
                ?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getSearchUrl($_term) ?>"
                   class="<?php echo $sizeClass; ?>">
                    <?php echo $block->escapeHtml($_term->getName()) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <div class="message notice">
        <div><?php /* @escapeNotVerified */ echo __('There are no search terms available.'); ?></div>
    </div>
<?php endif; ?>
