<?php 
	use Magento\Framework\App\Action\Action;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
    $StockState2 = $objectManager->get('\Magento\CatalogInventory\Api\StockConfigurationInterface');
	$category_load = $block->getCategory();
	$rows = 1;
	$enabled= $block->getConfig('enabled');
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	if($enabled && $category_load && strtotime($block->getConfig('end_date')) >= strtotime($block->getCurrentTime())){ 
		$image = 'category_image_primary_small';
?>1
<div class="hot-deal-tab-slider hot-deal-tab-slider-customcss">
	
	<div class="rows">
		<div class="block_superdeals_img"><?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('superdeals_img')->toHtml(); ?></div>
		<div class="hot-deal-slide">
			<div class="supper-deal-title">
				<?php if($this->getConfig('title')){?>
					<div class="rokan-product-heading rokan-onsale-heading">
						<h2 class="title-deal"><?php echo $this->getConfig('title')?> </h2>
						<h5 class="sub-title-deal"><?php echo __('Premium Natural Fruit Ice Cream') ?></h5>
						<p class="short-des"><?php echo __('Nam liber tempor cum soluta nobis eleifend option congue nihil doming id quod mazim placerat 
facer possim assum typi non habent claritatem insitam.') ?></p>
					</div>
				<?php }?>
			</div>
			<div class="countdown_block">
				<div class="title_countdown"><?php echo __('Fresh deal everyday. Get it before time runs out!') ?></div>
				<div class="super-deal-countdown" data-date="<?php echo $block->getConfig('end_date');?>"></div>
			</div>
			<p class="button-view"><a href="<?php echo $category_load->getUrl();?>" class="shop-now btn" data-hover="<?php echo __('Shop Now') ?>"><span><?php echo __('Shop Now') ?></span></a></p>
		</div>
	</div>
</div>
<script type="text/javascript">
require(["jquery", 'mage/mage','rokanthemes/timecircles', "rokanthemes/owl"], function($){
	'use strict';
		$( document ).ready(function() {
			$(".hot-deal-slide").owlCarousel({
				lazyLoad:true,
				items: 1,
	         	itemsDesktop : [1500, 1],
		        itemsDesktopSmall : [1199,1],
		        itemsTablet : [991, 1],
				itemsTabletSmall: [768, 1],
		        itemsMobile : [680, 1],
	        	navigation : true,
	        	pagination: false,
	         afterAction: function(el){
		     this.$owlItems.removeClass('first-active')
		     this.$owlItems .eq(this.currentItem).addClass('first-active')  
		  }
	    });

			if($('.super-deal-countdown').length>0){
				$(".super-deal-countdown").TimeCircles({
					fg_width: 0.01,
					bg_width: 1.2,
					text_size: 0.07,
					circle_bg_color: "#ffffff",
					time: {
						Days: {
							show: true,
							text: "<?php echo __('Days'); ?>",
							color: "#f9bc02"
						},
						Hours: {
							show: true,
							text: "<?php echo __('Hours'); ?>",
							color: "#f9bc02"
						},
						Minutes: {
							show: true,
							text: "<?php echo __('Mins'); ?>",
							color: "#f9bc02"
						},
						Seconds: {
							show: true,
							text: "<?php echo __('Secs'); ?>",
							color: "#f9bc02"
						}
					}
				}); 
			}
		});
    });
</script>
<?php } ?>