<?php 
	use Magento\Framework\App\Action\Action;
	$category_load = $block->getCategory();
	if($category_load && strtotime($block->getConfig('end_date')) >= strtotime($block->getCurrentTime())){ 
		$image = 'new_products_content_widget_grid';
	$deal_image = '';
	if($this->getConfig('deal_image')){
		$folderName = \Rokanthemes\Themeoption\Model\Config\Superdealsbannerimage::UPLOAD_DIR; 
		$path = $folderName . '/' . $this->getConfig('deal_image');
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		$imageUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$path;
		$deal_image = "<image src=".$imageUrl.">";
	}
?>
<div class="super-deal-banner"> 
		<div class="container">
			<div class="super-deal-banner-content <?php if($this->getConfig('deal_image')){?>row center_vertical<?php }?>">
				<?php if($this->getConfig('deal_image')){?>
					<div class="col-xs-12 col-md-5">
						<?php echo $deal_image ?>
					</div>
				<?php }?>
				<div class="col-countdown <?php if($this->getConfig('deal_image')){?>col-xs-12 col-md-6<?php }?>">
					<div class="supper-deal-title">
						<?php if($this->getConfig('title')){?><h5 class="sub-title-deal"><?php echo $block->getConfig('title');?></h5><?php }?>
						<?php if($this->getConfig('sub_title')){?><h2><?php echo __('Proud & Punch') ?></h2><h3 class="title-deal"><?php echo $block->getConfig('sub_title');?></h3><?php }?>
						<?php if($this->getConfig('description')){?><p class="short-des"><?php echo $block->getConfig('description');?></p><?php }?>
					</div>
					<div class="title_countdown"><?php echo __('Fresh deal everyday. Get it before time runs out!') ?></div>
					<div class="super-deal-countdown" data-date="<?php echo $block->getConfig('end_date');?>"></div>
					<p class="button-view"><a href="<?php echo $category_load->getUrl();?>" class="view-all-deal btn" data-hover="<?php echo __('Shop Now') ?>"><span><?php echo __('Shop Now') ?></span></a></p>
				</div>
			</div>  
		</div>
		
</div>
<script>
    require([
        'jquery',
        'rokanthemes/timecircles'
    ], function ($) {
		$( document ).ready(function() {
			if($('.super-deal-countdown').length>0){
				$(".super-deal-countdown").TimeCircles({
					fg_width: 0.01,
					bg_width: 1.2,
					text_size: 0.07,
					circle_bg_color: "#ffffff",
					time: {
						Days: {
							show: true,
							text: "<?php echo __('Days'); ?>",
							color: "#f9bc02"
						},
						Hours: {
							show: true,
							text: "<?php echo __('Hours'); ?>",
							color: "#f9bc02"
						},
						Minutes: {
							show: true,
							text: "<?php echo __('Mins'); ?>",
							color: "#f9bc02"
						},
						Seconds: {
							show: true,
							text: "<?php echo __('Secs'); ?>",
							color: "#f9bc02"
						}
					}
				}); 
			}
		});
    });
</script>
<?php } ?>