<div id="header" class="header-container">
	<div class="header-content">
		<div class="top-header">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-lg-6 hidden-xs hidden-sm">	
						<div class="top-bar-left">
							<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-left-static')->toHtml(); ?>
						</div>
					</div>
					<div class="col-xs-12 col-md-6 col-lg-6">
						<div class="top-bar-right">
							<div class="top-account has-child">
								<ul class="header links">
									<?php if(!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()){?>
										<li class="register-login hidden-xs authorization-link">
											<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/login/');?>"><?php echo __('Sign in or Register');?> </a>
										</li>
										<?php
									}
									else{
									?>	
									<li class="register-login hidden-xs">
										<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/');?>"><?php echo __('My Account');?></a>
									</li>
									<li class="register-login hidden-xs">
										<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/logout');?>"><?php echo __('Sign Out');?></a>
									</li>
									<?php } ?>
									<li class="register-login hidden-xs">
										<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('checkout/');?>"><?php echo __('Checkout');?></a>
									</li>	
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	    <div class="header">
	    	<div class="header_main">
		    	<div class="header-main">
	          		<div class="container">
	          			<div class="row">
				          	<div class="wp-header">
					            <div class="col-logo">
									<?php echo $this->getChildHtml("logo"); ?>
								</div>
					            <div class="top-search">
									<div class="flex-layout">
										<div class="col-header-action">
											<div class="top-info">
												<div class="top-account has-child">
													<!-- <a href="#"><?php // echo __('Account') ?></a> -->
													<?php echo $this->getChildHtml("top.links"); ?>
													
												</div>
											</div>
											<div class="mini-cart-wrapper shadowcart">
												  <div class="mini-carts">
													<?php echo $this->getChildHtml("minicart");?>
												  </div>
											 </div>
										</div> 
										<?php echo $this->getChildHtml("topSearch");?>
									</div> 
					            </div>	
					        </div>	
					    </div>
			        </div>    
		    	</div>
		    </div>
		    <div class="header-control header-nav cms_home_1">
		    	<div class="container">
		    		<div class="row">
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
						<div class="col-lg-2 col-md-3 col-sm-2 col-xs-6 menu_left_home1">
							<?php echo $this->getChildHtml("menu.vertical")?>
							<?php echo $this->getChildHtml("navigation-sections")?>
							<?php echo $this->getChildHtml("top.navigation.sections")?>
						</div>
						<div class="col-lg-7 col-md-7 col-sm-10 menu_primary hidden-xs">
							<div class="header-wrapper-sticky<?php echo (!$this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()) ? '' : ' enabled-header-sticky'; ?>">
								<div class="container-header-sticky">
									<div class="logo-sticky"><a href="<?php echo $block->getUrl('');?>" title="<?php echo __('Logo');?>"><img src="<?php echo ($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() != '') ? $this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() : $this->getViewFileUrl("images/logo_sticky.png");?>" alt="<?php echo __('Logo');?>"/></a></div>
									<div class="top-menu top-menu-sticky">
									  <?php echo $this->getChildHtml("custom.topnav"); ?>
									</div>
								</div>
							</div>
						</div>	
						<div class="col-lg-2 col-md-2 hidden-sm hidden-xs box_language">
							<!-- <?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('head_contact')->toHtml(); ?> -->
							<div class="top-header">
								<?php echo $this->getChildHtml("store_language"); ?>
								<?php echo $this->getChildHtml("currency"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
	    </div>
	</div>
</div>

