<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post list toolbar template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\PostList\Toolbar
 */
?>
<?php if ($block->getPagerHtml() !== '' ): ?>
    <div class="toolbar toolbar-blog-posts post-paginav">
        <?php echo $block->getPagerHtml() ?>
    </div>
<?php endif ?>
