<div class="top-home-content">
	<div class="container">
		<div class="banner-slider-top">
			<div class="col-xs-12 col-sm-9 block_slider">
				<div class="banner-slider banner-slider3">
					<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepageslider')->toHtml(); ?>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3 block_banner">
				<div>
					<div class="list-ads1">
						<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('list_ads1')->toHtml(); ?>
					</div>
				</div>
			</div>
		 </div>
	</div>
</div>
<script type="text/x-magento-init">
{
    ".top-home-content": {
        "Magento_Cms/js/top_home_tabs": {}
    }
}
</script>