<?php
/**
 * Copyright © 2016 TuanHatay. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Rokanthemes\VerticalMenu\Block\Verticalmenu
 */
?>
<?php
    $_helper = $this->helper('Rokanthemes\VerticalMenu\Helper\Data');
    $_config = $_helper->getConfig('verticalmenu');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
        $menuId = 'verticalmenu-main-' . uniqid();
?>
<?php $_menu = $block->getVerticalMenuHtml(); ?>

<nav class="navigation verticalmenu" id="<?php echo $menuId; ?>">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/x-magento-init">
{
    "#<?php echo $menuId; ?>": {
        "Rokanthemes_VerticalMenu/js/topmenu": {}
    }
}
</script>
<?php
    } else {
?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation verticalmenu">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>

<?php
    }
?>