<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$title = $block->getTitle();
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);
?>
<div class="rokan-product-heading">
	<?php echo $title ? '<h2>'.$title.'</h2>' : ''; ?>	
	<p class="short_des"><?php echo __('Commodo sociosqu venenatis cras dolor sagittis integer luctus sem primis 
eget maecenas sed urna malesuada.'); ?></p>
</div>
<div class="rows">
	<?php if(count($categoryIds) > 0) : ?>
		<div class="wrap-category">
		<?php $iterator = 1; 
			$i = 0;
			$rows = 1;
		?>
		<ul class="owl">
			<?php foreach($categoryIds as $key => $cate_id) : ?>
				<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
					<li class='wp-item'>	
						<div class="item">
							<div class="popcat-box">
								<?php 
									$cate_model =  $block->getCategory($cate_id);
									$subCate = $block->getCategoryList($cate_model->getChildren());
							   	?>
								<div class="category-info">
									<h3><a href="<?php echo $cate_model->getUrl() ?>"><?php echo $cate_model->getName(); ?></a></h3>
								    <ul class="sub-categories">
								   		<?php foreach ($subCate as $key => $value): ?>
											<li><a href="<?php echo $value->getUrl(); ?>"><?php echo $value->getName(); ?></a></li>
								   		<?php endforeach; ?>
								    </ul>				    	
							    </div>
							   	<div class="wp category-item">
								   	<a href="<?php echo $cate_model->getUrl() ?>">
								    	<img src="<?php echo $this->helper('Rokanthemes\Categorytab\Helper\Data')->getThumbnailImageUrl($cate_model) ?>" alt="<?php echo $cate_model->getName() ?>" />
								    </a>
								</div>
							</div>
						</div>
					</li>
				<?php if($i%$rows==0) { ?> </div> <?php }?>
			<?php endforeach; ?>
			</ul>
		</div>
	<?php endif; ?>
</div>

<script>
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';
		jQuery(".wrap-category .owl").owlCarousel({
			lazyLoad:true,
			autoPlay : false,
			items : 5,
			itemsDesktop : [1399,4],
			itemsDesktopSmall : [1199,3],
			itemsTablet: [767,2],
			itemsMobile : [480,1],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : false,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
			pagination : false,
		     afterAction: function(el){
		     this.$owlItems.removeClass('first-active');
		     this.$owlItems .eq(this.currentItem).addClass('first-active');  
		    }
		});
	});
</script>