<?php
/**
 * Copyright © 2016 TuanHatay. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Rokanthemes\VerticalMenu\Block\Verticalmenu
 */
?>
<?php
    $_helper = $this->helper('Rokanthemes\VerticalMenu\Helper\Data');
    $_config = $_helper->getConfig('verticalmenu');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getVerticalMenuHtml(); ?>

<nav class="navigation verticalmenu side-verticalmenu">
	<h2 class="title-category-dropdown"><span><?php echo __('Shop By Department'); ?></span></h2>
    <ul class="togge-menu list-category-dropdown menu-hidden">
        <?php echo $_menu; ?>
        <li class="expand-category-link">
        	<a href="#"><?php echo __('All Categories') ?></a>
        </li>
        		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vertical_background_images')->toHtml();?>
	</ul>

</nav>

<script type="text/x-magento-init">
    {
        ".navigation.verticalmenu": {
            "Rokanthemes_VerticalMenu/js/sidemenu": {
                "limitItemShow": <?php echo $block->getConfig('limit_show'); ?>
            }
        }
    }
</script>
<?php
    }
?>
