<div id="header" class="header-container compare-wishlist-icon">
	<div class="header-content">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-topbar-image7')->toHtml(); ?>
	    <div class="header">
	    	<div class="header_main">
		    	<div class="header-main">
	          		<div class="container">
	          			<div class="row">
				          	<div class="wp-header">
					            <div class="col-md-2 col-sm-2 col-xs-12">
									<?php echo $this->getChildHtml("logo"); ?>
								</div>
								 <div class="hidden-sm hidden-md hidden-lg col-xs-8">
								 	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menu_links_mobile')->toHtml(); ?>
								 </div>
					            <div class="col-md-10 col-sm-10 col-xs-12 top-search">
									<div class="flex-layout">
										<div class="col-header-action">
											<div class="top-info">
												<div class="top-account has-child">
													<!-- <a href="#"><?php // echo __('Account') ?></a> -->
													<?php echo $this->getChildHtml("top.links"); ?>
													
												</div>
											</div>
											<div class="mini-cart-wrapper shadowcart">
												  <div class="mini-carts">
													<?php echo $this->getChildHtml("minicart");?>
												  </div>
											 </div>
										</div> 
										<?php echo $this->getChildHtml("topSearch");?>
									</div> 
					            </div>	
					        </div>	
					    </div>
			        </div>    
		    	</div>
		    </div>
		    <div class="header-control header-nav cms_home_1">
		    	<div class="container">
		    		<div class="row"> 
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
						<div class="col-lg-9 col-md-9 col-sm-12 menu_primary hidden-xs">
							<div class="header-wrapper-sticky<?php echo (!$this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()) ? '' : ' enabled-header-sticky'; ?>">
								<div class="container-header-sticky">
									<div class="logo-sticky"><a href="<?php echo $block->getUrl('');?>" title="<?php echo __('Logo');?>"><img src="<?php echo ($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() != '') ? $this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getStickyLogoHeader() : $this->getViewFileUrl("images/logo_sticky.png");?>" alt="<?php echo __('Logo');?>"/></a></div>
									<div class="top-menu top-menu-sticky">
									  <?php echo $this->getChildHtml("custom.topnav"); ?>
									</div>
								</div>
							</div>
						</div>	
						<div class="col-lg-3 col-md-3 hidden-sm hidden-xs box_language">
							<div class="top-header">
								<?php echo $this->getChildHtml("store_language"); ?>
								<?php echo $this->getChildHtml("currency"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
	    </div>
	</div>
</div>

