<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Framework\View\Element\Template */
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a title="<?= $block->escapeHtmlAttr(__('Compare Products')) ?>"
       data-bind="attr: {'href': compareProducts().listUrl}"
    >
        <i class="compare_Products"></i> <?= $block->escapeHtml(__('Compare')) ?>
        <!-- ko if: compareProducts().count -->
        <span class="counter qty" data-bind="text: '('+compareProducts().count+')'"></span>
        <!-- /ko -->
        <!-- ko if: !compareProducts().count -->
        <span data-bind="text: '(0)'" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>