<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
$b2bHelper = $this->helper('GrupoAwamotos\B2B\Helper\Data');
?>
<?php if ($b2bHelper->isHidePrice()): ?>
    <!-- Hidden for Guest -->
<?php else: ?>
    <?php if ($_product->isSaleable()): ?>
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="attr-product">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="info-qty">
                <a class="qty-down" href="#"><i class="fa fa-minus"></i></a>
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Quantity') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <a class="qty-up" href="#"><i class="fa fa-plus"></i></a>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart addcart-link"
                    id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        },
        "*": {
            "Magento_Catalog/js/product_qty": {}
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/handle_add_to_cart": {}
        },
        "*": {
            "Magento_Catalog/js/product_qty": {}
        }
    }
</script>
<?php endif; ?>