<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php
$helper = $this->helper('Magento\Catalog\Helper\Product');
$shareUrl = $this->escapeUrl('https://www.facebook.com/sharer.php?u=' . rawurlencode($block->getProductUrl($_product)));
$emailUrl = $helper->getEmailToFriendUrl($_product);
?>
<div class="product-social-actions" data-mage-init='{"Magento_Catalog/js/product/share-print":{"windowName":"Facebook","windowFeatures":"width=500,height=500"}}'>
    <?php if ($block->canEmailToFriend()): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Email') ?>" href="<?php /* @escapeNotVerified */ echo $emailUrl ?>"
           class="action email-link"><i class="fa fa-envelope"></i></a>
    <?php endif; ?>
    <a href="#" title="<?php /* @escapeNotVerified */ echo __('Print') ?>" class="action print-link" data-role="print-link"><i class="fa fa-print"></i></a>
    <a href="<?php echo $shareUrl; ?>" title="<?php /* @escapeNotVerified */ echo __('Share') ?>" class="action share-link" data-role="share-link" target="_blank" rel="noopener">
        <i class="fa fa-share"></i>
    </a>
</div>