<?php

use \Magento\Framework\Stdlib\StringUtils;

/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Rokanthemes\Blog\Block\Sidebar\Recent
 */
?>

<?php

	$stringFilter = new \Magento\Framework\Stdlib\StringUtils;
	$enable = $this->getConfig('enable_frontend');
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('default');
	$desktop = $this->getConfig('desktop');
	$desktop_small = $this->getConfig('desktop_small');
	$tablet = $this->getConfig('tablet');
	$mobile = $this->getConfig('mobile');
	$pagination = $this->getConfig('pagination');
	$show_next_back = $this->getConfig('show_next_back');
	$show_navigation_control = $this->getConfig('show_navigation_control');
	$title = $this->getConfig('title');
	$shortdec = $this->getConfig('shortdec');
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
	$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count() && $enable) { ?>
<section class="widget box-section block-recent-posts" data-bind="scope: 'recemt-posts'">
		<div class="rokan-product-heading rokan-onsale-heading">
			<h2><?php echo __($title) ?> <span class="sup-title"> <?php echo __('Blog') ?></span></h2>
			<p class="short-dec">
				<?php  echo __($shortdec) ?> 
			</p>
		</div>
		<div class="row">
			<div class="owl-container">
				<div class="block-content">
					<div class="owl">
						<?php foreach ($_postCollection as $_post) { ?>
							<div class="product-item">
								<div class="item-blog">
									<div class="blog-image">
										<a href="<?php echo $_post->getPostUrl() ?>">
											<img alt="<?php echo $_post->getTitle(); ?>" src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>" />
										</a>
									</div>
									<div class="blog-content">
										<div class="blog-info">
											<div class="post-tags-info">
												<?php 
												$name_c = '';
												$name_d = '';
												$cate = $_post->getParentCategories();
												if(count($cate) > 0){
												    	foreach($cate as $cat){
												    		$name_c = $cat->getTitle();
												    		$name_d = $cat->getUrl();
												    		break;
												    	}
												    }
											 ?>
												 <a href="<?php echo $name_d; ?>"> <?php echo $name_c; ?> </a>
											</div>
											<div class="time-conment">
												<?php 
													$date = $_post->getPublishTime();
												?>
												Post Date: 
												<span class="date-time"><span class="date"><?php echo __(date("d", strtotime($date))) ?></span><span class="separator">-</span><span class="month"><?php echo __(date("M", strtotime($date))) ?></span>-<span class="year"><?php echo __(date("Y", strtotime($date))) ?></span></span>
											</div>
											<h3 class="blog-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a>
											</h3>
											<div class="short-des">
												<?php $length = 350; ?>
												<div class="text-description"><?php echo $stringFilter->substr($_post->getShortContent(),0,$length); ?></div>
											</div>
											<a class="readmore btn" href="<?php echo $_post->getPostUrl() ?>">
												<span class="readmore-text"> <?php echo __('Continue reading') ?></span>
											</a>
										</div>
										
									</div>
								</div>
							</div>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
</section>

<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery(".block-recent-posts .owl").owlCarousel({
			lazyLoad:true,
			items : 3,
			margin: 30,
			itemsDesktop : [1199,3],
			itemsDesktopSmall : [991,3],
			itemsTablet: [768,2],
			itemsMobile : [480,1],
			slideSpeed : <?php echo $pagination; ?>,
			paginationSpeed : <?php echo $pagination; ?>,
			rewindSpeed : <?php echo $pagination; ?>,
			addClassActive: true,
			navigation : <?php echo $show_next_back; ?>,
			stopOnHover : true,
			pagination : <?php echo $show_navigation_control; ?>,
			scrollPerPage:true,
		});
	});
</script>
<?php } ?>