<?php
$testimonials = $block->getCollection();
$helperImage = $this->helper('Rokanthemes\Testimonials\Helper\Image');
$helperData = $this->helper('Rokanthemes\Testimonials\Helper\Data');
$allRating = $block->getAllRating();
if($block->isAllowCustomerSubmit())
{
	if($block->isAllowGuestSubmit())
		$urlNew = $block->getNewUrl();
	else{
		if($this->checkLogin())
			$urlNew = $block->getNewUrl();
		else
			$urlNew = $this->getUrl('customer/account/login');
	}
	$showSubmit = true;
}else{
	$showSubmit = false;
}
?>
<?php if($helperData->isEnabled()):?>
<div class="page-testimonial">
	<div class="testimonial-slider">
		<div class="paginav-slider">
			<div class="wrap-item">
				<?php if ($testimonials && count($testimonials)){ ?>
					<?php foreach ($testimonials as $_testimonial){ ?>
						<div class="item">
							<div class="testimo-item">
								<div class="row">
									<div class="col-md-3 col-sm-12 col-xs-12">
										<div class="testimo-content-left" style="text-align: center;margin-right: 20px;">
											<div class="info-testimo-author">
												<?php $website='#'; if($_testimonial['website']):?>
													<?php $website = $_testimonial['website'];?>
												<?php endif;?>
												<?php  $link = $helperImage->resize($_testimonial['avatar'],120,120, true);?>
												<a href="<?php echo $website ?>">
												   <img style="width: 100%;border-radius: 100%;" alt="<?php echo $_testimonial['name']; ?>" src="<?php echo $link ?>" title="<?php echo $block->escapeHtml($_testimonial['name']) ?>"/>
												</a>
												<h3 class="testimo-name" style="margin-top: 10px;"><a href="<?php echo $website ?>"><?php echo $_testimonial['name']; ?></a></h3>
												<p class="testimo-job"><?php echo $_testimonial['job']; ?></p>
											</div>
										</div>
									</div>
									<div class="col-md-9 col-sm-12 col-xs-12">
										<div class="testimo-content-right">
											<div class="testimo-desc"><?php echo $block->getFilterTestimonials($_testimonial['testimonial']); ?></div>
											<span class="testimo-date"><?php echo date('F d Y',strtotime($_testimonial['created_time'])); ?></span>
										</div>
									</div>
								</div>
							</div>
						</div>
					<?php } ?>
				<?php } ?>
			</div>
		</div>
	</div>
	<div class="customer-saying">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('customer_saying')->toHtml(); ?>
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';
	jQuery(document).ready(function ($) {
		$('.testimonial-slider .wrap-item').owlCarousel({
			lazyLoad:true,
			items: 2,
			itemsCustom: [ 
			[0, 1], 
			[480, 1], 
			[768, 2], 
			[992, 2], 
			[1200, 2] 
			],
			pagination: false,
			navigation: false,
		});
	});
});
</script>
<?php endif;?>