<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
if($banners = $block->getBannerCollection()):
	$slider = $block->getSlider();
	$sliderId = $block->getSliderId(); 
?>
<div class="wrapper_slider hidden-xs slider_<?php echo $sliderId; ?>">
	<div class="owl">
		<?php foreach($banners as $banner){ if($banner->getSlideStatus() == '2'){ continue; }	?>
			<div class="banner_item">
				<div class="banner_item_bg">
					<?php
					$html = $block->getImageElement($banner->getSlideImage());
					if($link = $banner->getSlideLink())
						$html = '<a href="'. $link .'">' . $html . '</a>' ; 
					echo $html;
					?>
				</div>	
				<div class="text-banner">
					<?php if($text = $banner->getSlideText()){
						echo $block->getContentText($text); 
					}
					?>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
<div class="wrapper_slider visible-xs slider_<?php echo $sliderId; ?>_mobile">
	<div class="owl">
		<?php foreach($banners as $banner){  if($banner->getSlideStatus() == '2'){ continue; }	?>
			<div class="banner_item">
				<div class="banner_item_bg">
					<?php
					$html = $block->getImageElement($banner->getSlideImageMobile());
					if($link = $banner->getSlideLink())
						$html = '<a href="'. $link .'">' . $html . '</a>' ; 
					echo $html;
					?>
				</div>	
				<div class="text-banner">
					<?php if($text = $banner->getSlideText()){
						echo $block->getContentText($text); 
					}
					?>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
<script>
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';
		jQuery(".slider_<?php echo $sliderId; ?>_mobile .owl").owlCarousel(
			{
				lazyLoad:true,
				<?php foreach($slider->getSliderSetting() as $key=>$value)
				{
					if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
						if($value == 1){
							$value = 'true';
						}
						else{
							$value = 'false';
						}
					}
					echo $key . ':' . $value . ',';
				} ?>}
		);
		jQuery(".slider_<?php echo $sliderId; ?> .owl").owlCarousel(
			{
				lazyLoad:true,
				<?php foreach($slider->getSliderSetting() as $key=>$value)
				{
					if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
						if($value == 1){
							$value = 'true';
						}
						else{
							$value = 'false';
						}
					}
					echo $key . ':' . $value . ',';
				} ?>}
		);
		$(document).ready(function() {
			//Function to animate slider captions 
			function doAnimations( elems ) {
				//Cache the animationend event in a variable
				var animEndEv = 'webkitAnimationEnd animationend';
				
				elems.each(function () {
					var $this = $(this),
						$animationType = $this.data('animation');
					$this.addClass($animationType).one(animEndEv, function () {
						$this.removeClass($animationType);
					});
				});
			}
			//Variables on page load 
			var $myCarousel = $('.wrapper_slider'),
				$firstAnimatingElems = $myCarousel.find('.text-banner').find("[data-animation ^= 'animated']");
			//Animate captions in first slide on page load 
			doAnimations($firstAnimatingElems);

		});
	});
</script>
<?php endif; ?>
