<?php 
	use Magento\Framework\App\Action\Action;
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getSlideRow();
	$title = $block->getTitle(); 
	$identify = trim($block->getIdentify()); 
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);

	$productsOnRow = 2 ;
	if(!$productsOnRow) $productsOnRow = 4;
?>

<div class="categorytab-container cat_1">
	<div class="rokan-product-heading rokan-featured-heading clearfix">
		<?php echo $title ? '<h2 class="pull-left">'.$title.' <span class="sup-title">'. __('Product') .'</span></h2>' : ''; ?>
		<div class="vc_tta-tabs-container pull-right">
		  	<ul class="tabs tabs<?php echo '-'.$identify;?>"> 
			   <?php 
				$k = 0;
				foreach($categoryIds as $cate_id) {
					$cate_model =  $block->getCategory($cate_id);
					$cateName = $cate_model->load($cate_id)->getName();
					if($cateName) {
			   ?>
					<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo trim($cate_id).'-'.$identify;?>"><a><?php  echo $cateName; ?></a></li>
				<?php }  $k++; } ?>
		    </ul>
		</div>
	</div>
	<div class="row">	
		<div class="vc_tta-tabs-position-top">
			<div class="vc_tta-panels-container"> 
			     <?php 
					$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
					$image = 'category_image_primary_small';
					$type = 'widget-new-grid';
					$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
				?>
				<div class="tab_container tab_container2"> 
					<?php foreach($categoryIds as $cate_id) { ?>
					<div id="tab<?php echo trim($cate_id).'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
							 
						<div class="owl-container">
							<div class="cat_home cat_home2 owl-carousel">
								<?php 
								$newItems =  $block -> getProductCate($cate_id)->getItems(); 
								$i=0;
								foreach($newItems as $_item) { 
									$productImage = $block->getImage($_item, $image);
								?>
								<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
									<div class="item-product">
										<div class="product-thumb">
											<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product-thumb-link">
												<?php $productImageThumb = $block->getImage($_item, 'category_image_second_small');?>
												<span class="first-thumb">
													<?php echo $productImage->toHtml(); ?>
												</span>
												<?php $productType = $_item->getTypeID();
												if($productType == "simple"): ?>
													<span class="second-thumb">
														<?php echo $productImageThumb->toHtml(); ?>
													</span>
						                		<?php endif; ?>
											</a>
											<div class="hot-onsale">
												<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
													
														<span class="onsale">
														<span class="sale-bg"></span>
														<span class="sale-text"><?php echo $block->showLableSalePrice($_item); ?>
														</span>
														</span>
												<?php endif; ?>
												<?php $helper = $this->helper('Rokanthemes\RokanBase\Helper\Newlabel'); ?>
													<?php if($helper->isProductNew($_item)): ?>
													<div class="onsale new-lable">
													    <?php echo __('New'); ?>
													</div>
												<?php endif; ?>
											</div>
											<div class="actions-secondary">
												<ul class="product-extra-link add-to-links">
												<?php if ($showWishlist || $showCompare): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
													<li>
														<a href="#"
														   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
														   class="wishlist-link action towishlist" data-action="add-to-wishlist"
														   title="<?php echo __('Add to Wishlist') ?>">
														</a>
													</li>
													<?php endif; ?>
													<li class="quickview-product">
														<a class="quickview-link" data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="javascript: void(0);" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="<?php echo __('Quick view');?>">
														</a>
													</li>
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
														<li>
															<a href="#" class="compare-link action tocompare"
															   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
															   title="<?php echo __('Add to Compare') ?>">
															</a>
														</li>
							                        
														<?php endif; ?>
													<?php endif; ?>
												</ul>										
										    </div>
										    <div class="product-info-cart">
								                <?php if ($showWishlist || $showCompare || $showCart): ?>
								                	<?php if ($showCart): ?>
									                    <div class="actions-primary addcart-link">
									                      <?php if ($_item->isSaleable()): ?>
									                        <?php
									                          $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
									                          $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
									                          $postParams = json_decode($postData, true);
									                          ?>
									                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
									                          <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
									                          <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
									                          <?php echo $block->getBlockHtml('formkey')?>
									                          <button type="submit"
									                              title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
									                              class="btn-add-to-cart action tocart">
									                            <span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
									                          </button>
									                        </form>
									                      <?php else: ?>
									                        <?php if ($_item->getIsSalable()): ?>
									                          <div class="stock available"><span><?php echo __('In stock') ?></span></div>
									                        <?php else: ?>
									                          <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
									                        <?php endif; ?>
									                      <?php endif; ?>
									                    </div>
									                <?php endif; ?>
								                 
					  							<?php endif; ?>
				  							</div>						
									    </div>
									    <div class="product-info">
											<h3 class="product-name">
					 							<a title="<?php echo $_item->getName(); ?>" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product-item-link">
													<?php echo $_item->getName(); ?>
												</a>
											</h3>
											<div class="product-rating">
												<?php if ($templateType): ?>
			   										<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
			   									<?php endif; ?>
											</div>
											<div class="sold-by">
												<?php
													$cats = $_item->getAttributeText('sold_by');
													echo ' <span>'.__('Sold by:').'</span>' .$cats;
												 ?>
											</div>
											<div class="info-price">
												<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_item)) ?>
											</div>
										</div>
									</div>

										
										<?php if($i%$rows==0 || $i == count($newItems)) { ?> </div> <?php }?>
								<?php 
								}
								?>
							</div>
						</div>	
						
					 </div><!-- #tab1 -->
					<?php }?>
				</div>
			</div>
		 </div> <!-- .tab_container --> 
	</div>
</div>
<script type="text/x-magento-init">
{
	"[data-role=tocart-form], .form.map.checkout": {
		"catalogAddToCart": {}
	}
}
</script>
<script type="text/javascript">
require([
	'jquery',
	'mage/mage',
	'rokanthemes/owl'
], function ($) {
	'use strict';

	jQuery(".tab_content_<?php echo $identify; ?>").hide();
	jQuery(".tab_content_<?php echo $identify; ?>:first").show(); 

	jQuery("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
		jQuery("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
		jQuery(this).addClass("active");
		jQuery(".tab_content_<?php echo $identify; ?>").hide();
		var activeTab = $(this).attr("rel"); 
		jQuery("#"+activeTab).show(); 
	});
	$( document ).ready(function() {	
	 $(".cat_home2").owlCarousel({
		 lazyLoad:true,
	 	items : 7,
        itemsDesktop : [1366, 5],
        itemsDesktopSmall : [1199, 4],
        itemsTablet : [991, 3],
        itemsMobile : [680, 2],
	    navigation : true,
	    pagination : false,
	     afterAction: function(el){
	     this.$owlItems.removeClass('first-active')
	     this.$owlItems .eq(this.currentItem).addClass('first-active')  
	    }
	});
	});
	
});
 

</script> 