<?php 
  $helper = $this->helper('Rokanthemes\RokanBase\Helper\Data');
	$enableMenu = $helper ->getConfigData('themeoption/footer/footer_menu_mobile');
?>
<div class="page_footer">
  <div id="footer" class="footer-container layout2 footer">
      <?php echo $this->getChildHtml("footer_static14"); ?>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
          <?php  echo $this->getLayout()->createBlock("Rokanthemes\Themeoption\Block\Customcss")->setTemplate("html/copyright.phtml")->toHtml() ?>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
          <?php echo $this->getChildHtml("footer_payment"); ?>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="fixed-right">
  <?php echo $this->getChildHtml("fixed_right"); ?>
</div>
<div class="shadow_bkg"></div>
<div class="shadow_bkg_show"></div>
<div id="back-top" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
<?php if($enableMenu){ ?>
<div class="fixed-bottom hidden-sm hidden-md hidden-lg">
  <div class="link-on-bottom">
    <ul class="mobile-bottom-link flex-layout space-between list-unstyled">
      <li><a href="<?php echo $this->getUrl('');?>"><span class="icon icon-chrome"></span><?= $block->escapeHtml(__('Home')) ?></a></li>
      <li><a href="#" class="toggle-nav-footer"><span class="icon icon-menu"></span><?= $block->escapeHtml(__('Menu')) ?></a></li>
      <li><a href="<?php echo $this->getUrl('customer/account/');?>"><span class="icon icon-users"></span><?= $block->escapeHtml(__('Account')) ?></a></li>
      <li><a href="<?php echo $this->getUrl('checkout/cart/');?>"><span class="icon icon-shopping-cart"></span><?= $block->escapeHtml(__('Cart')) ?></a></li>
      
    </ul>
  </div>
</div>
<?php } ?>
<script type="text/javascript">
  require([
      'jquery',
      'mage/mage',
      'rokanthemes/owl'
    ], function ($) {
      'use strict';
    $( document ).ready(function() {
     $(".block-content.brandowl-play >ul").owlCarousel({
     lazyLoad:true,
        items : 7,
        itemsDesktop : [1366, 5],
            itemsDesktopSmall : [991,3],
            itemsTablet : [767, 2],
            itemsMobile : [479, 1],
          navigation : true,
           afterAction: function(el){
           this.$owlItems.removeClass('first-active')
           this.$owlItems .eq(this.currentItem).addClass('first-active')  
          }
      });
    });
    var responsiveflag = false;

    $(document).ready(function(){
      responsiveResize();
      $(window).resize(responsiveResize);
    });
    function responsiveResize()
    {
      if ($(window).width() <= 767 && responsiveflag == false)
      {
        accordionFooter('enable');
        responsiveflag = true;
      }
      else if ($(window).width() >= 768)
      {
        accordionFooter('disable');
        responsiveflag = false;
      }
    }
    function accordionFooter(status)
    {
      if(status == 'enable')
      {
        $('.velaFooterMenu h4.velaFooterTitle').on('click', function(e){
          $(this).toggleClass('active').parent().find('.velaContent').stop().slideToggle('medium');
          e.preventDefault();
        })
      }
      else
      {
        $('.velaFooterMenu h4.velaFooterTitle').removeClass('active').off().parent().find('.velaContent').slideDown('fast');
      }
    }
  });
</script>  