<?php 
	use Magento\Framework\App\Action\Action;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
    $StockState2 = $objectManager->get('\Magento\CatalogInventory\Api\StockConfigurationInterface');
	$category_load = $block->getCategory();
	$rows = 1;
	$enabled= $block->getConfig('enabled');
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	if($enabled && $category_load && strtotime($block->getConfig('end_date')) >= strtotime($block->getCurrentTime())){
		$image = 'category_image_primary_small';
?>
<?php if($this->getConfig('title')){?>
	<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo $this->getConfig('title')?>  <span class="sup-title"><?php echo __('Of The Day') ?></span></h2></div>
<?php }?>
<div class="hot-deal-tab-slider hot-deal-tab-slider-customcss">
	<div class="countdown_block">
		<div class="title_countdown"><?php echo __('Hurry Up! Offer ends in:') ?></div>
		<div class="super-deal-countdown" data-date="<?php echo $block->getConfig('end_date');?>"></div>
	</div>
	<div class="row">
		<div class="hot-deal-slide">
			<?php 
				$newItems =  $block->getProducts();
				$i=0;
				foreach($newItems as $_item) { 
					$productImage = $block->getImage($_item, $image);
				?>
				<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
					<div class="item-product product-item">
						<div class="content-item-product">
							<div class="product-thumb">
								<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product-thumb-link">
									<?php $productImageThumb = $block->getImage($_item, 'category_image_second_small');?>
									<span class="first-thumb">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<?php $productType = $_item->getTypeID();
									if($productType == "simple"): ?>
										<span class="second-thumb">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
			                		<?php endif; ?>
								</a>
								<div class="hot-onsale">
									<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
										
											<span class="onsale">
											<span class="sale-bg"></span>
											<span class="sale-text"><?php echo $block->showLableSalePrice($_item); ?>
											</span>
											</span>
									<?php endif; ?>
									<?php $helper = $this->helper('Rokanthemes\RokanBase\Helper\Newlabel'); ?>
										<?php if($helper->isProductNew($_item)): ?>
										<div class="onsale new-lable">
										    <?php echo __('New'); ?>
										</div>
									<?php endif; ?>
								</div>
								<div class="actions-secondary">
									<ul class="product-extra-link add-to-links">
										<li class="wishlist-product">
											<a href="#"
											   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
											   class="wishlist-link action towishlist" data-action="add-to-wishlist"
											   title="<?php echo __('Add to Wishlist') ?>">
											</a>
										</li>
										<li class="quickview-product">
											<a  class="quickview-link" data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="javascript: void(0);" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="<?php echo __('Quick view');?>">
											</a>
										</li>
										<li class="compare-product">
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
											<a href="#" class="compare-link action tocompare"
											   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
											   title="<?php echo __('Add to Compare') ?>">
											</a>
										</li>
									</ul>										
							    </div>
							    <div class="product-info-cart">
				                    <div class="actions-primary addcart-link">
				                      <?php if ($_item->isSaleable()): ?>
				                        <?php
				                          $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
				                          $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
				                          $postParams = json_decode($postData, true);
				                          ?>
				                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
				                          <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
				                          <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
				                          <?php echo $block->getBlockHtml('formkey')?>
				                          <button type="submit"
				                              title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
				                              class="btn-add-to-cart action tocart">
				                            <span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
				                          </button>
				                        </form>
				                      <?php else: ?>
				                        <?php if ($_item->getIsSalable()): ?>
				                          <div class="stock available"><span><?php echo __('In stock') ?></span></div>
				                        <?php else: ?>
				                          <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
				                        <?php endif; ?>
				                      <?php endif; ?>
				                    </div>
	  							</div>							
						    </div>
						    <div class="product-info">
								<h3 class="product-name">
		 							<a title="<?php echo $_item->getName(); ?>" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product-item-link">
										<?php echo $_item->getName(); ?>
									</a>
								</h3>
								<div class="product-rating">
									<?php if ($templateType): ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
									<?php endif; ?>
								</div>
								<div class="sold-by">
									<?php
										$cats = $_item->getAttributeText('sold_by');
										echo ' <span>'.__('Sold by:').'</span>' .$cats;
									 ?>
								</div>
								<div class="info-price">
									<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_item)) ?>
								</div>
								<div class="product-sold">
									<?php 
										$numbertotal = $StockState->getStockQty($_item->getId());
										$numbersold = $StockState2->getMaxSaleQty();
										$calculator = (($numbertotal - $numbersold) / $numbertotal) * 100;
									?>
									<div class="ruler-sold">
										<div class="ruler-sold-count" style="width: <?php 
											echo $calculator; ?>%;">
										</div>
									</div>
									<div class="count-sold">
										Sold: 
										<?php 
											if ($numbersold >= $numbertotal) {
												echo $numbertotal.'/'.$numbertotal;
											}else{
												echo ($numbertotal - $numbersold).'/'.$numbertotal;
											}
										?>
									</div>
								</div>
							</div>
						</div>
					</div>
						<?php if($i%$rows==0 || $i == count($newItems)) { ?> </div> <?php }?>
				<?php 
				}
				?>
		</div>
	</div>
</div>
<script type="text/javascript">
require(["jquery", 'mage/mage','rokanthemes/timecircles', "rokanthemes/owl"], function($){
	'use strict';
		$( document ).ready(function() {
			$(".hot-deal-slide").owlCarousel({
				lazyLoad:true,
				items: 6,
	         	itemsDesktop : [1366, 5],
		        itemsDesktopSmall : [1199, 4],
		        itemsTablet : [991, 3],
		        itemsMobile : [680, 2],
	        	navigation : true,
	        	pagination: false,
	         afterAction: function(el){
		     this.$owlItems.removeClass('first-active')
		     this.$owlItems .eq(this.currentItem).addClass('first-active')  
		  }
	    });

			if($('.super-deal-countdown').length>0){
				$(".super-deal-countdown").TimeCircles({
					fg_width: 0.01,
					bg_width: 1.2,
					text_size: 0.07,
					circle_bg_color: "#ffffff",
					time: {
						Days: {
							show: true,
							text: "<?php echo __('Days'); ?>",
							color: "#f9bc02"
						},
						Hours: {
							show: true,
							text: "<?php echo __('Hours'); ?>",
							color: "#f9bc02"
						},
						Minutes: {
							show: true,
							text: "<?php echo __('Mins'); ?>",
							color: "#f9bc02"
						},
						Seconds: {
							show: true,
							text: "<?php echo __('Secs'); ?>",
							color: "#f9bc02"
						}
					}
				}); 
			}
		});
    });
</script>
<?php } ?>