<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$textmss = 'Enter your email and <span class="text-primary">25% off</span> off your first purchase!';
?>
<div id="newsletter_pop_up" class="newsletterpopup">
	<div class="btn-close newletter_popup_close"></div>
		<div class="newletter-poup">
			<div class="title"><h3><?php echo __('Luckyshop'); ?></h3></div>
			<div class="content">
				<form class="form subscribe"
					novalidate
					action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
					method="post"
					data-mage-init='{"validation": {"errorClass": "mage-error"}}'
					id="newsletterpopup-validate-detail">
					<div class="field newsletter">
						<div class="des-newletter">
							<?php echo $textmss; ?>
						</div>
						<div class="control">
							<input name="email" type="email" id="newsletterpopup"
										placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>" data-validate="{required:true, 'validate-email':true}" />
						</div>
					</div>
					<div class="actions">
						<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
							<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
						</button>
					</div>
					<div class="subscribe-bottom">
						<input type="checkbox" id="newsletter_popup_dont_show_again">
						<label for="newsletter_popup_dont_show_again"><?php echo __("Don't shop this popup again")?></label>
					</div>
				</form>
				
			</div>
		</div>
</div>
<?php  
	$top = 120; 
	$speed= 500; 
	$timeout = 1;
?>

<script type="text/x-magento-init">
    {
        "#newsletter_pop_up": {
            "Rokanthemes_Newsletterpopup/js/newsletter": {
                "top": <?php echo $top; ?>,
                "speed": <?php echo $speed; ?>,
                "timeout": <?php echo $timeout; ?>
            }
        }
    }
</script>