<div class="top-home-content">
		<div class="banner-slider banner-slider2">
			<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage9slider')->toHtml(); ?>
		</div>
</div>
<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_top')->toHtml(); ?>
		<div class="new_product">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>
		</div>
		<div class="banner_mid_1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner1_mid_home9')->toHtml(); ?>
		</div>
		
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category1_home9')->toHtml(); ?>

		<div class="block-testimonials">
			<div class="row">
				<div class="col-lg-6 col-md-6 hidden-sm">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner2_mid_home9')->toHtml(); ?>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home9_why_cu')->toHtml(); ?>
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Testimonials\Block\Testimonials')->setTemplate('Rokanthemes_Testimonials::slider.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
</div>
		<div class="block_notification">
			<div class="container">
				<marquee direction="" onmouseover="this.stop();" onmouseout="this.start();">
				<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('notification_home9')->toHtml(); ?>
				</marquee>
			</div>
		</div>
<div class="top-home-content">
	<div class="container">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category2_home9')->toHtml(); ?>
		<div class="the_blog">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
</div>
<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand_section')->toHtml(); ?>
	</div>
</div>
