<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-onsaleproduct">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo $this->getConfig('title')?> <span class="sup-title"> <?php echo __('Products') ?></span></h2></div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-onslate-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = 3;
			?>	
			<div class="row">
					<ul class="owl_onsale">
						<?php $_collectionSize = $_productCollection->count() ?>
						<?php $i=0; foreach ($_productCollection as $_product): ?>
							<?php if($i %$rows == 0) echo "<li class='item onsaleproductslider-item'>"; ?>

								<div class="item-product">
									<?php
									$newFromDate = $_product->getNewsFromDate();
									$newToDate = $_product->getNewsToDate();                 
									$now = date("Y-m-d H:m(worry)");
									// Get the Special Price
									$specialprice = $_product->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = $_product->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = $_product->getSpecialToDate();
									// Get Current date
									if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)){
										echo "<span class='icon-sale icon-product'><?php echo __('Sale') ?></span>";
									}else{
									if($newFromDate <= $now && $newToDate >= $now) {
										echo "<span class='icon-new icon-product'><?php echo __('Hot') ?></span>";
									 		//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
									 	}
									}
									?>
									<?php
									$productImage = $block->getImage($_product, $image);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
									?>
									<?php // Product Image ?>
									<div class="product-thumb">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-thumb-link">
												<?php $productImageThumb = $block->getImage($_product, 'category_image_second_small');?>
												<span class="first-thumb">
													<?php echo $productImage->toHtml(); ?>
												</span>
												<?php $productType = $_product->getTypeID();
												if($productType == "simple"): ?>
													<span class="second-thumb">
														<?php echo $productImageThumb->toHtml(); ?>
													</span>
						                		<?php endif; ?>
											</a>
									</div>
									<div class="product-info">
											<?php
												$_productNameStripped = $block->stripTags($_product->getName(), null, true);
											?>
											<h3 class="product-name">
					 							<a title="<?php echo $_product->getName(); ?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-link">
													<?php echo $_product->getName(); ?>
												</a>
											</h3>
											<div class="product-rating">
												<?php if ($templateType): ?>
													<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
												<?php endif; ?>
											</div>
											<div class="sold-by">
													<?php
														$cats = $_product->getAttributeText('sold_by');
														echo ' <span>'.__('Sold by:').'</span>' .$cats;
													 ?>
												</div>
											<div class="info-price">
												<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
											</div>

										</div>
								<?php $i++;?>
							</div>
							<?php if($i %$rows == 0) echo "</li>"; ?>                  
						<?php endforeach; ?>
							<?php if($i %$rows != 0) echo "</li>"; ?>                
					</ul>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-onsaleproduct .owl_onsale").owlCarousel({
						lazyLoad:true,
						autoPlay : false,
						items : 1,
						itemsDesktop : [1366,1],
						itemsDesktopSmall : [1199,1],
						itemsTablet: [768,1],
						itemsMobile : [480,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : false,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
						afterAction: function(el){
						    this.$owlItems.removeClass('first-active')
						    this.$owlItems .eq(this.currentItem).addClass('first-active')  
					    }
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>