<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog available for import template
 *
 * @var $block \Magento\Backend\Block\Template
 */
?>

<table class="available-imports">
	<tr>
		<td>
			<a class="itm-hld" href="<?php echo $block->getUrl('blog/import/wordpress') ?>">
				<img src="<?php echo $this->getViewFileUrl('Rokanthemes_Blog::images/wordpress.png') ?>" alt="WordPress" />
				<span class="lable">Import from WordPress (beta)</span>
			</a>
		</td>
		<td></td>
		<td></td>
		<td></td>
	<tr>
</table>
