<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span>
        
    </strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
				<?php 
					$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
					$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
					$currentStore = $storeManager->getStore();
				?>
                <?php if($flag = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('general/country/flag', 'store',$block->getCurrentStoreCode())){ ?>
                    <img alt="<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>" src="<?php echo $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'logo/' . $flag; ?>" />
                <?php } ?>
                <span><?php echo $currentStore->getName(); ?><i class="fa fa-angle-down">&nbsp;</i></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
            <li class="action toggle switcher-trigger <?php if ($_lang->getId() == $block->getCurrentStoreId()): ?>active<?php endif; ?>" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $_lang->getId()?>">
                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                    <?php if($flag = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('general/country/flag', 'store', $_lang->getCode())): ?>
                    <img alt="<?php echo $_lang->getName(); ?>" src="<?php echo $_lang->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'logo/' . $flag; ?>" />
                    <?php else: ?>
                    <span><?= $block->escapeHtml($_lang->getName()) ?></span>
                    <?php endif; ?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<?php endif; ?>