<div class="top-home-content">
		<div class="banner-slider banner-slider2">
			<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage11slider')->toHtml(); ?>
		</div>
</div>
<div class="top-home-content">
	<div class="container">
		<div class="banner_mid_1 first">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner1_mid_home11')->toHtml(); ?>
		</div>
		<div class="banner_mid_1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner2_mid_home11')->toHtml(); ?>
		</div>
	</div>
	<div class="banner_mid_1 banner_background">
		<div class="container text-banner">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner3_mid_home10')->toHtml(); ?>
		</div>
	</div>
	<div class="container">
		<div class="banner_mid_1 last">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner2_mid_home10')->toHtml(); ?>
		</div>
		<div class="the_blog">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
	<div class="shipping_support_fashion">
		<div class="container">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_support_fashion_2')->toHtml(); ?>
		</div>
	</div>
	
</div>                   
