<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$title = $block->getTitle();
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);
?>
<div class="rokan-product-heading">
	<?php echo $title ? '<h2>'.$title.' <span class="sup-title">'. __('categories') .'</span></h2>' : ''; ?>	
</div>

<div class="rows">
	<?php if(count($categoryIds) > 0) : ?>
		<div class="wrap-category">
		<?php $iterator = 2; 
			$i = 0;
			$rows = 2;
		?>
		<div class="owl">
			<?php foreach($categoryIds as $key => $cate_id) : ?>
				<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
					<div class="wp-item">
						<div class="item">
							<div class="popcat-box">
								<?php 
									$cate_model =  $block->getCategory($cate_id);
									$subCate = $block->getCategoryList($cate_model->getChildren());
								?>
								<div class="category-info">
									<h3><a href="<?php echo $cate_model->getUrl() ?>">#<?php echo $cate_model->getName(); ?></a></h3>
									<p>(<?php echo $cate_model->getProductCount(); ?> <?php echo __('items)') ?></p>
									<!-- <ul class="sub-categories">
										<?php foreach ($subCate as $key => $value): ?>
											<li><a href="<?php echo $value->getUrl(); ?>"><?php echo $value->getName(); ?></a></li>
										<?php endforeach; ?>
									</ul> -->
								</div>
								<div class="wp category-item">
									<a href="<?php echo $cate_model->getUrl() ?>">
										<img src="<?php echo $this->helper('Rokanthemes\Categorytab\Helper\Data')->getThumbnailImageUrl($cate_model) ?>" alt="<?php echo $cate_model->getName() ?>" />
									</a>
								</div>
							</div>
						</div>
					</div>
				<?php if($i%$rows==0) { ?> </div> <?php }?>
			<?php endforeach; ?>
			</div>
		</div>
	<?php endif; ?>
</div>

<script type="text/x-magento-init">
    {
        ".wrap-category .owl": {
            "Rokanthemes_Categorytab/js/catthumbnail": {}
        }
    }
</script>