<div class="top-home-content">
		<div class="banner-slider banner-slider2">
			<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage15slider')->toHtml(); ?>
		</div>
</div>
<div class="top-home-content">
	<div class="banner_mid_1 first">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner1_mid_home15')->toHtml(); ?>
	</div>
	<div class="container">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?>
	</div>
	<div class="block_category_thumb">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_thumb_15')->toHtml(); ?>
	</div>
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category1_home15')->toHtml(); ?>
	</div>
	<div class="banner_mid_1 banner_background">
		<div class="container text-banner">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner3_mid_home10')->toHtml(); ?>
		</div>
	</div>
	<div class="the_blog">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
	
</div>                   
