<?php
	$helperData = $this->helper('Rokanthemes\Testimonials\Helper\Data');
	$helperImage = $this->helper('Rokanthemes\Testimonials\Helper\Image');
	if(!$helperData->isEnabled()) return false;
	$_testimonialsCollection = $block->getTestimonials();
	$title = $block->getTitle();
	$img_width = $helperData->getImgRizeWidth();
	$img_height = $helperData->getImgRizeHeight();
?>
<?php if ($_testimonialsCollection->count()):?>
<div class="box-bottom-home2 box-testimo">
	<h2><?php echo __($title) ?></h2>
	<div class="testimo-slider slider-home2">
		<div class="wrap-item">
			<?php foreach ($_testimonialsCollection as $_testimonial) { ?>
				<div class="item-testimo">
					<div class="testimonialContent">
						<div class="desc">
								<?php echo $_testimonial->getTestimonial();?>
						</div>
					</div>
					<div class="info-testimonial">
						<div class="author-test-info">
							<h3><a href="#"><?php echo $_testimonial->getName(); ?></a></h3>
							<span> - <?php echo $_testimonial->getJob(); ?></span>
						</div>
						<div class="author-testimo">
							<div class="author-test-link">
								<?php  $link = $helperImage->resize($_testimonial->getAvatar(),$img_width,$img_height, true);?>
								<a href="#"><img src="<?php echo $link;?>" alt="" /></a>
							</div>
						</div>
							
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
</div>
<script type="text/x-magento-init">
    {
        ".testimo-slider": {
            "Rokanthemes_Testimonials/js/testimonials": {}
        }
    }
</script>
<?php else :?>
<div class="box-bottom-home2 box-testimo">
  <span><?php echo __('Testimonial records not available.'); ?></span>
</div>
<?php endif; ?>