<div class="top-home-content">
	<div class="container">
		<div class="gird-layout">
			<div class="banner-slider banner-slider2">
				<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage12slider')->toHtml(); ?>
			</div>
			<div class="banner_mid_1 hidden-xs">
				<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner1_mid_home12')->toHtml(); ?>
			</div>
		</div>
	</div>
</div>
<div class="top-home-content">
	<div class="container">
		<div class="banner_mid_1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner2_mid_home12')->toHtml(); ?>
		</div>
		<div class="new_product">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?>
		</div>
		<div class="banner_mid_1 hover-effect-animation">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner3_mid_home12')->toHtml(); ?>
		</div>
		<div class="group product"> 
			<div class="row">
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?>				
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml();?>
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Featuredpro\Block\Featured')->setTemplate('Rokanthemes_Featuredpro::featured.phtml')->toHtml();?> 
				</div>
			</div>
		</div>
		<div class="the_blog">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>

	</div>
	<div class="instagram-home12">
		<div class="container">
			<div class="title-instagram"><h3><?php  echo __('Follow') ?> <span><?php  echo __('@Ayo') ?></span> <?php  echo __('On Instagram') ?></h3></div>
		</div>
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('instagram_static')->toHtml(); ?>
	</div>
</div>
