<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$categorySelectId = preg_replace('/[^A-Za-z0-9_-]/', '', (string)$block->getNameInLayout());
if ($categorySelectId === '') {
    $categorySelectId = uniqid('categoryselect_');
}
$categorySelectId = 'choose-category-' . $categorySelectId;
?>
<div class="block block-search">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <select name="cat" id="<?php echo $categorySelectId; ?>">
						<option value=""><?php echo __('All Categories'); ?></option>
					<?php $categories = $block->getCategories(); 
					foreach($categories as $cat)
					{
						?>
						<option value="<?php echo $cat->getId(); ?>"><?php echo $cat->getName(); ?></option>
						<?php
					}
					?>
					</select>
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span class="flaticon-magnifying-glass34"></span>
                </button>
            </div>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
{
	"#<?php echo $categorySelectId; ?>": {
		"Rokanthemes_SearchSuiteAutocomplete/js/category-select": {}
	}
}
</script>