<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-bestseller">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = 3;
			?>	
			<div class="row">
				<ul class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<li class='item bestsellerslider-item'>"; ?>

							<div class="item-product"> 
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php // Product Image ?>
								<?php // Product Image ?>
								<div class="product-thumb">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-thumb-link">
											<?php $productImageThumb = $block->getImage($_product, 'category_image_second_small');?>
											<span class="first-thumb">
												<?php echo $productImage->toHtml(); ?>
											</span>
											<?php $productType = $_product->getTypeID();
											if($productType == "simple"): ?>
												<span class="second-thumb">
													<?php echo $productImageThumb->toHtml(); ?>
												</span>
											<?php endif; ?>
										</a>
								</div>
								<div class="product-info">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<h3 class="product-name">
										<a title="<?php echo $_product->getName(); ?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-link">
											<?php echo $_product->getName(); ?>
										</a>
									</h3>
									<div class="product-rating">
										<?php if ($templateType): ?>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
										<?php endif; ?>
									</div>
									<div class="sold-by">
													<?php
														$cats = $_product->getAttributeText('sold_by');
														echo ' <span>'.__('Sold by:').'</span>' .$cats;
													 ?>
												</div>
									<div class="info-price">
										<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
									</div>

								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</li>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>                
				</ul>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-bestseller .owl").owlCarousel({
						lazyLoad:true,
						autoPlay : false,
						items : 1,
						itemsDesktop : [1199,1],
						itemsDesktopSmall : [980,1],
						itemsTablet: [768,1],
						itemsMobile : [479,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : false,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					});
				});
			</script>
	<?php endif; ?>
	</div>
 
<?php } ?>