<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post js template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
    $addThisConfig = [
        'pubId' => 'ra-4def63cd3cf37569',
        'language' => 'en',
        'trackClickback' => false
    ];
?>
<script type="text/x-magento-init">
{
    "body": {
        "Rokanthemes_Blog/js/addthis": <?php echo json_encode($addThisConfig, JSON_UNESCAPED_SLASHES); ?>
    }
}
</script>