<div class="top-home-content">
		<div class="banner-slider banner-slider2">
			<?php echo $this->getLayout()->createBlock('Rokanthemes\SlideBanner\Block\Slider')->setslider_id('homepage16slider')->toHtml(); ?>
		</div>
</div>
<div class="top-home-content">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_top')->toHtml(); ?>
		<div class="banner_mid_1">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner1_mid_home9')->toHtml(); ?>
		</div>
		<div class="bestsellerproduct">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?>
		</div>

	</div>
</div>
<div class="block_notification">
	<div class="container">
		<marquee direction="" onmouseover="this.stop();" onmouseout="this.start();">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('notification_home9')->toHtml(); ?>
		</marquee>
	</div>
</div>
<div class="hot-deal">
	<?php echo $block->getLayout()->createBlock('Rokanthemes\Superdeals\Block\ProductByCat')->setTemplate('Rokanthemes_Superdeals::deal-banner.phtml')->toHtml();?>
</div>		
<div class="cat_home16">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category1_home16')->toHtml(); ?>
	</div>
</div>
<div class="top-home-content">
	<div class="block-why-makes">
		<div class="container">
			<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_why_makes')->toHtml(); ?>
		</div>
	</div>
	<div class="container">
		<div class="the_blog">
		<?php echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
</div>
